export interface AttackInfo {
  slug: string;
  detector: string;
  name: string;
  category: string;
  severity: 'high' | 'medium';
  summary: string;
  example: string;
  handling: string;
  importance: string;
  defense: string;
}

export const attacks: AttackInfo[] = [
  { slug: 'sql-injection', detector: 'SQL Injection', name: 'SQL Injection', category: 'Web Security', severity: 'high', summary: 'Malicious SQL instructions are placed inside normal user input.', example: "admin' UNION SELECT * FROM users--", handling: 'Scans query parameters and request bodies for SQL keywords, quotes, comments, and UNION patterns. A match is logged and blocked.', importance: 'A successful SQL injection can expose, change, or delete database records.', defense: 'Use parameterized queries, an ORM, least-privilege database accounts, and input validation.' },
  { slug: 'xss', detector: 'XSS', name: 'Cross-Site Scripting', category: 'Web Security', severity: 'high', summary: 'JavaScript is injected into content that may be displayed in another user’s browser.', example: '<script>alert(document.cookie)</script>', handling: 'Looks for script tags, event handlers such as onerror, and javascript: URLs in submitted values.', importance: 'XSS can steal sessions, modify pages, or perform actions as another user.', defense: 'Encode output by context and deploy a strong Content Security Policy.' },
  { slug: 'path-traversal', detector: 'Path Traversal', name: 'Path Traversal', category: 'System Security', severity: 'high', summary: 'Relative path sequences are used to escape an allowed folder.', example: '../../../etc/passwd', handling: 'Inspects the URL and request values for ../, encoded equivalents, and sensitive operating-system paths.', importance: 'It may expose configuration, passwords, source code, or other private server files.', defense: 'Normalize paths, enforce an allowed root directory, and use least-privilege file permissions.' },
  { slug: 'command-injection', detector: 'Command Injection', name: 'Command Injection', category: 'System Security', severity: 'high', summary: 'Shell operators are added to input so the server executes an unintended command.', example: '; cat /etc/shadow', handling: 'Detects shell separators followed by common commands such as cat, rm, whoami, or ls.', importance: 'Successful command injection can provide complete control of the application server.', defense: 'Avoid shell execution and use native library functions or strict allow-lists.' },
  { slug: 'brute-force', detector: 'Brute-Force Login', name: 'Brute-Force Login', category: 'Authentication', severity: 'high', summary: 'Many passwords are tried rapidly against one account.', example: 'admin + five different wrong passwords', handling: 'Tracks failed login timestamps by IP and username. Five failures within 30 seconds trigger an alert.', importance: 'Automated guessing can compromise accounts that use weak passwords.', defense: 'Use MFA, progressive delays, rate limits, and secure account-lockout rules.' },
  { slug: 'credential-stuffing', detector: 'Credential Stuffing', name: 'Credential Stuffing', category: 'Authentication', severity: 'high', summary: 'One leaked password is tested against many different usernames.', example: 'same leaked password → user1, user2, user3…', handling: 'Tracks the distinct usernames targeted by each IP and password combination.', importance: 'Password reuse allows credentials leaked from another service to compromise your users.', defense: 'Use MFA, breached-password checks, device analysis, and login rate limits.' },
  { slug: 'ddos', detector: 'Request Flood / DDoS', name: 'Request Flood / DDoS', category: 'Network Security', severity: 'high', summary: 'A client sends enough requests to exhaust application resources.', example: '50 requests in less than 10 seconds', handling: 'Counts recent requests by IP, logs the threshold breach, blocks the IP, and removes the block after 30 seconds.', importance: 'Flooding can make the API unavailable to legitimate users.', defense: 'Use CDN/WAF rate limiting, load balancing, caching, and network-level filtering.' },
  { slug: 'ssrf', detector: 'SSRF Attempt', name: 'Server-Side Request Forgery', category: 'Cloud Security', severity: 'high', summary: 'The server is tricked into requesting an internal or cloud-only address.', example: 'http://169.254.169.254/latest/meta-data/', handling: 'Parses the supplied fetch URL and rejects localhost, private IPv4 ranges, and cloud metadata addresses.', importance: 'Internal services may trust the application server and expose credentials or administration APIs.', defense: 'Allow-list destinations, validate DNS results, block metadata networks, and restrict outbound traffic.' },
  { slug: 'file-upload', detector: 'Malicious File Upload', name: 'Malicious File Upload', category: 'File Security', severity: 'high', summary: 'An executable or script is disguised with an innocent file extension.', example: 'Windows MZ executable renamed to innocent.png', handling: 'Checks the uploaded file’s real magic bytes for Windows executables, PHP scripts, and shell scripts.', importance: 'A malicious upload could lead to code execution or infect users who download it.', defense: 'Re-encode allowed files, store them outside the web root, and scan them in an isolated service.' },
  { slug: 'scanner', detector: 'Scanner / Attack Tool', name: 'Scanner Tool Detection', category: 'Reconnaissance', severity: 'high', summary: 'Automated security tools probe the API for known weaknesses.', example: 'User-Agent: sqlmap/1.5.8', handling: 'Compares the User-Agent header against signatures for sqlmap, Nikto, Nmap, DirBuster, and similar tools.', importance: 'Automated reconnaissance often comes before exploitation attempts.', defense: 'Combine WAF signatures with behavioral detection because User-Agent values can be changed.' },
  { slug: 'enumeration', detector: 'Endpoint Enumeration', name: 'Endpoint Enumeration', category: 'Reconnaissance', severity: 'medium', summary: 'Many guessed URLs are requested to discover hidden files or administration pages.', example: '/admin, /backup, /.env → repeated 404 responses', handling: 'Counts 404 responses per IP and reports 15 missing endpoints requested within 20 seconds.', importance: 'Enumeration reveals the application’s attack surface and forgotten endpoints.', defense: 'Monitor abnormal 404 ratios, use rate limits, and remove unused or sensitive public routes.' }
];
